export const signUpURL = "https://tem-dado-em-casa-api.onrender.com/sign-up";
export const loginURL = "https://tem-dado-em-casa-api.onrender.com/sign-in";
export const productsURL = "https://tem-dado-em-casa-api.onrender.com/products";
export const cartURL = "https://tem-dado-em-casa-api.onrender.com/cart";
export const orderURL = "https://tem-dado-em-casa-api.onrender.com/orders";
/* export const signUpURL = "http://localhost:5000/sign-up";
export const loginURL = "http://localhost:5000/sign-in";
export const productsURL = "http://localhost:5000/products";
export const cartURL = "http://localhost:5000/cart"; */
